server:
  port: 8088
spring:
  jackson:
    time-zone: Europe/Budapest
  kafka:
    listener:
      ack-mode: record
    bootstrap-servers: 127.0.0.1:29092
    consumer:
      # ha nincs @KafkaListener-ben groupId, add meg itt:
      group-id: ${spring.application.name:-app}-grp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      client.dns.lookup: use_all_dns_ips

management:
  server:
    port: 9088
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      app: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    hu.porkolab.chaosSymphony: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"