server:
  port: 8095

spring:
  jackson:
    time-zone: Europe/Budapest
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    listener:
      ack-mode: record
    consumer:
      group-id: ${spring.application.name:-app}-grp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 10
        batch.size: 32768
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      client.dns.lookup: use_all_dns_ips

management:
  server:
    port: 9095
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    hu.porkolab.chaosSymphony: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
