server:
  port: 8082

kafka:
  topic:
    payment:
      requested: payment.requested
      requested.canary: payment.requested.canary
      dlt: payment.requested.dlt
  group:
    id:
      payment: payment-requested
      payment.canary: payment-requested-canary

spring:
  application:
    name: payment-svc
  datasource:
    url: jdbc:h2:mem:payment;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: none
  sql:
    init:
      mode: always
  jackson:
    time-zone: Europe/Budapest
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    retry:
      max-attempts: 5
      initial-interval-ms: 300
      multiplier: 2.5
      max-interval-ms: 3000
    listener:
      ack-mode: record
      type: single
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 10
        batch.size: 32768
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      client.dns.lookup: use_all_dns_ips

management:
  server:
    port: 9082
  metrics:
    tags:
      app: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    hu.porkolab.chaosSymphony: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

payment:
  processing:
    success-rate: 0.9

chaos:
  retry:
    strategy: exponential
    max-attempts: 4
    initial-interval-ms: 300
    multiplier: 2.0
    max-interval-ms: 5000

---
spring:
  config:
    activate:
      on-profile: chaos
chaos:
  retry:
    strategy: exponential
    max-attempts: 6
    initial-interval-ms: 500
    multiplier: 2.0
    max-interval-ms: 15000

---
spring:
  config:
    activate:
      on-profile: ci
chaos:
  retry:
    strategy: fixed
    max-attempts: 2
    initial-interval-ms: 200
