spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    driver-class-name: org.postgresql.Driver
    username: app
    password: app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
