server:
  port: 8089

spring:
  jackson:
    time-zone: Europe/Budapest
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    listener:
      ack-mode: record
    consumer:
      group-id: ${spring.application.name:-app}-grp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      client.dns.lookup: use_all_dns_ips
  
  
  
  
  security:
    oauth2:
      resourceserver:
        jwt:
          
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8180/realms/chaos-symphony}
          
          


security:
  mode: ${SECURITY_MODE:jwt}  

management:
  server:
    port: 9089
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG
    hu.porkolab.chaosSymphony: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
